apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

configMapGenerator:
- name: foo-app-configuration
  envs:
  - properties.env

secretGenerator:
- name: foo-app-secured-configuration
  envs:
  - secured.env