version: '3.5'

services:

  postgres:
    container_name: foo-db
    image: postgres:10.5
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
      POSTGRES_DB: foo-db
    networks:
    - tracing-demo

  # jaeger:
  #   container_name: jaeger
  #   image: jaegertracing/all-in-one:latest
  #   hostname: jaeger
  #   ports:
  #     - 5778:5778
  #     - 16686:16686
  #     - 14268:14268
  #   networks:
  #   - acme

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus
  #   hostname: prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   # ports:
  #   #   - 9090:9090
  #   network_mode: host

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana
  #   hostname: grafana
  #   depends_on:
  #     - prometheus
  #   # ports:
  #   #   - 3000:3000
  #   volumes:
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/:z
  #   environment:
  #     - PROMETHEUS_URL=http://prometheus:9090
  #   network_mode: host

networks:
  tracing-demo:
    driver: bridge
