## SPRING
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    initialization-mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

# OPENTRACING
opentracing:
  jaeger:
    log-spans: true
    http-sender:
      url: ${JAEGER_COLLECTOR}
    service-name: distributed-tracing-demo-simple
