apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: foo-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: foo-app:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/clbartolome/distributed-tracing-demo
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-11:1.3
        namespace: openshift
    type: Source
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  triggers: 
  - type: "ConfigChange"