apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: foo-app
  app.openshift.io/runtime: spring-boot
  app.kubernetes.io/component: foo-app
  app.kubernetes.io/instance: foo-app

resources:
- buildConfig.yaml
- imageStream.yaml
- deployment.yaml
- service.yaml
- route.yaml